# Generated by Django 3.0.3 on 2020-03-19 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191129_0845'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('products', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User')),
            ],
        ),
    ]
