# Generated by Django 3.0.3 on 2020-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payement_id',
            field=models.CharField(default='COD', max_length=250),
        ),
        migrations.AlterField(
            model_name='payement',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
