# Generated by Django 3.0.3 on 2020-03-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200319_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='status',
            field=models.CharField(default='Fail', max_length=250),
        ),
    ]
