# Generated by Django 3.0.3 on 2020-03-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200319_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
