# Generated by Django 2.2.6 on 2019-10-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='alternative_phone',
            new_name='alternate_phone',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='s_name',
            new_name='l_name',
        ),
    ]
