# Generated by Django 2.2.6 on 2019-10-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191029_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='inactive', max_length=250),
        ),
    ]
