# Generated by Django 2.2.6 on 2019-11-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191030_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logined',
            field=models.BooleanField(default=False),
        ),
    ]
