# Generated by Django 2.2.6 on 2019-11-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_logined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='alternate_phone',
            field=models.CharField(max_length=250),
        ),
    ]
