# Generated by Django 2.2.6 on 2019-11-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191107_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='pin',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
