# Generated by Django 3.0.5 on 2020-06-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191129_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='address_type',
            field=models.CharField(default='home', max_length=250),
        ),
    ]
