# Generated by Django 2.2.6 on 2019-10-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('rear_camera', models.CharField(max_length=200)),
                ('front_camera', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('and_ver', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('rom', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
        ),
    ]
