# Generated by Django 2.2.6 on 2019-10-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_special',
            new_name='is_exclusive',
        ),
    ]
