# Generated by Django 2.2.6 on 2019-10-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20191012_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
