# Generated by Django 2.2.6 on 2019-10-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('hdmi', models.IntegerField(max_length=2)),
                ('usb', models.IntegerField(max_length=2)),
                ('sound_output', models.CharField(max_length=200)),
                ('smart_tv', models.BooleanField(default=False)),
                ('build_in_wifi', models.BooleanField(default=False)),
                ('youtube_support', models.BooleanField(default=False)),
                ('netflix_support', models.BooleanField(default=False)),
                ('refresh_rate', models.CharField(max_length=200)),
                ('tv_type', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('ssd', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('hdd', models.CharField(max_length=200)),
                ('graphic_card', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('graphic_memory', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
        ),
    ]
