# Generated by Django 2.2.6 on 2019-10-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tv',
            name='hdmi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tv',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tv',
            name='usb',
            field=models.IntegerField(),
        ),
    ]
