# Generated by Django 2.2.6 on 2019-10-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20191024_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('dial_shape', models.CharField(max_length=200)),
                ('water_resistance', models.BooleanField(default=False)),
                ('strap_material', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=200)),
                ('charge_time', models.CharField(max_length=200)),
                ('battery_life', models.CharField(max_length=200)),
                ('call_function', models.CharField(max_length=200)),
                ('wifi', models.BooleanField(default=False)),
                ('gps', models.BooleanField(default=False)),
                ('sensor', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('hdmi', models.IntegerField()),
                ('usb', models.IntegerField()),
                ('sound_output', models.CharField(max_length=200)),
                ('smart_tv', models.BooleanField(default=False)),
                ('build_in_wifi', models.BooleanField(default=False)),
                ('youtube_support', models.BooleanField(default=False)),
                ('netflix_support', models.BooleanField(default=False)),
                ('refresh_rate', models.CharField(max_length=200)),
                ('tv_type', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
        ),
    ]
