# Generated by Django 3.0.2 on 2020-02-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200202_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(height_field='image_height', upload_to='photos/%y/%m/%d', width_field='image_width'),
        ),
    ]
