# Generated by Django 3.0.2 on 2020-02-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200205_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
    ]
