# Generated by Django 2.2.6 on 2019-10-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
