# Generated by Django 2.2.6 on 2019-10-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='unique_id',
        ),
    ]
